-- Create profiles table
create table public.profiles (
  id uuid references auth.users not null primary key,
  name text,
  surname text,
  email text,
  gender text,
  birth_date date,
  bulugh_date date,
  profile_image text,
  last_processed_date date,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "Users can insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

-- Create debt_counts table
create table public.debt_counts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  type text not null,
  count int default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, type)
);

-- Enable RLS for debt_counts
alter table public.debt_counts enable row level security;

create policy "Users can view own debts" on public.debt_counts
  for select using (auth.uid() = user_id);

create policy "Users can update own debts" on public.debt_counts
  for update using (auth.uid() = user_id);

create policy "Users can insert own debts" on public.debt_counts
  for insert with check (auth.uid() = user_id);

-- Create daily_status table
create table public.daily_status (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date date not null,
  type text not null, -- 'prayer' or 'fasting'
  status text, -- 'completed', 'missed', etc.
  note text,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, date, type)
);

-- Enable RLS for daily_status
alter table public.daily_status enable row level security;

create policy "Users can view own daily status" on public.daily_status
  for select using (auth.uid() = user_id);

create policy "Users can update own daily status" on public.daily_status
  for update using (auth.uid() = user_id);

create policy "Users can insert own daily status" on public.daily_status
  for insert with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name, surname)
  values (
    new.id, 
    new.email,
    new.raw_user_meta_data->>'name',
    new.raw_user_meta_data->>'surname'
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
